### PR TITLE
Move all $http invocations into new services module (#11)

### PR DESCRIPTION
**Pull request by ZachMoreno**
I'm happy to do this for the `license_content` array once it is moved into its own JSON file. If that is not already in the works, I'm happy to open an issue and handle that.

Thanks!

### CODE REVIEW

**Comment by ZachMoreno** [comment]
Also, my CLA has already been submitted for my contributions on Open MCT. Kim Chrestenson can confirm.

**Comment by addyosmani** [comment]
@jasonduley would it be possible to hook this repo up to the CLA bot? (or do we not need to?). Just checking before we start merging in community contributions.

**Comment by ZachMoreno** [comment]
Sorry, I'm not sure why my PR for addressing #14 is now included in this PR. Is there a way to separate them into 2 PRs? Or can we merge as is, addressing both #12 & #14?

**Comment by addyosmani** [comment]
@ZachMoreno Could you rebase this PR against master please? https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Pull request closed without merging**
